environment:
  matrix:
  - node_version: "6"
  - node_version: "8"
  - node_version: "Current"

install:
  - ps: Install-Product node $env:node_version
  - choco install yarn
  - refreshenv
  - yarn install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
